language: python
cache: pip
dist: xenial
sudo: false
python:
  - '3.8'
  - '3.7'
  - '3.6'
before_install:
  - python --version
  - pip install pip tox-travis coverage coveralls flake8
install:
  - pip install ".[test]"
script: tox
after_success:
  - coveralls
  - flake8 --statistics --count